### ISSUE TITLE
layout module can not be found

### ISSUE THREAD

**Issue by ferrinweb** [SinanMtl/vue-focus-keyboard#2]
The log:
`This relative module was not found:

* ./scripts/layout in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-focus-keyboard/src/FocusKeyboard.vue
`

layout.js export module by 'module.exports', but use 'import' to load the layout module in FocusKeyboard.vue

**Comment by ferrinweb** [comment]
'scripts' directory dose not exist, and where i can find 'vue-focus-keyboard\src\assets\icons.pug' file?

**Comment by ferrinweb** [comment]
I have solved these mistakes myself, see files.zip at attachments.

[files.zip](https://github.com/SinanMtl/vue-focus-keyboard/files/1824519/files.zip)

**Comment by SinanMtl** [comment]
Fixed this problem.
